service: prisoner-ipsum-api

provider:
  name: aws
  runtime: nodejs10.x

functions:
  ipsum:
    handler: handler.ipsum
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-offline
